version: '3'

volumes:
  gems:
    driver: ${VOLUMES_DRIVER}
  node_modules:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}

services:

  rails:
    build:
      context: ./docker/ruby
      args:
        - UID=${RUBY_UID}
        - GID=${RUBY_GID}
    environment:
      - DATABASE_ADAPTER=${DATABASE_ADAPTER}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
    volumes:
      - .:/app
      - gems:/gems
      - node_modules:/app/node_modules
    ports:
      - "${RAILS_SERVER_HOST_PORT}:3000"
    command: bundle exec rails server -p 3000 -b 0.0.0.0
    entrypoint: docker/ruby/rails-entrypoint.sh
    user: ruby
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - postgres:/var/lib/postgresql/data
