name: Production Image Workflow

on:
  check_suite: 
    types: [completed]

env:
  IMAGE_NAME: ruby-prod

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.check_suite.conclusion == 'success'
    steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Log into registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build Production Image
      run: docker build . --file docker/production/Dockerfile
