name: CI
on: [push]

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
  RAILS_ENV: test
  RACK_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    container: circleci/ruby:2.6.6-node-browsers
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: Gems Cache
      id: gem-cache
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundle Install
      run: bundle check || bundle install --path vendor/bundle --jobs 4 --retry 3

    - name: Prepare DB
      run: bundle exec rails db:schema:load --trace

    - name: RSpec Suite
      run: |
        bundle exec rspec --format progress \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress
