name: Run Tests
on: [push]

env:
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
  RAILS_ENV: test
  RACK_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ['5432:5432']
        # needed because the postgres container does not provide a healthcheck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2

    - name: No Docs
      run: "echo 'gem: --no-document' >> ~/.gemrc"

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.5

    - name: RubyGems Update
      run: gem update --system

    - name: Gems Cache
      id: gem-cache
      uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-

    - name: Bundle Install
      run: bundle check || bundle install --path vendor/bundle --jobs 4 --retry 3

    - name: Get Yarn Cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Node Modules Cache
      id: node-modules-cache
      uses: actions/cache@v2
      with:
        path: |
          ${{ steps.yarn-cache.outputs.dir }}
          node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn Install
      run: yarn check || bin/rails yarn:install

    - name: Prepare DB
      run: bundle exec rails db:schema:load --trace

    - name: RSpec and Report Coverage
      run: |
        bundle exec rspec --format progress \
                          --format RspecJunitFormatter \
                          --out /tmp/test-results/rspec.xml \
                          --format progress
